version: '3.9'
volumes:
  mysql-volume:
services:
  nginx:
    image: nginx:latest
    ports:
      - 5050:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    #  - ./www/html:/var/www/html
      - ./server:/var/www
    depends_on:
      - php

  php:
    ports:
      - 5173:5173
    build: ./php
    volumes:
    #  - ./www/html:/var/www/html
        - ./server:/var/www
    depends_on:
      - db 

  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: db-host
    ports:
      - 13306:3306
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
        MYSQL_DATABASE: private_chat
        MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin:5
    ports:
      - 8888:80
    depends_on:
      - db