version: '3.9'
volumes:
  mysql-volume:
services:
  nginx:
    image: nginx:latest
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    #  - ./www/html:/var/www/html
      - ./server:/var/www
    depends_on:
      - php

  php:
    ports:
      - ${VITE_PORT}:5173
    build: ./php
    volumes:
    #  - ./www/html:/var/www/html
        - ./server:/var/www
    depends_on:
      - db 

  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: db-host
    ports:
      - ${DB_PORT}:3306
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  phpmyadmin:
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin:5
    ports:
      - ${PHP_MYADMIN_PORT}:80
    depends_on:
      - db